# Generated by Django 5.1.7 on 2025-03-13 21:28

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('role',
                 models.CharField(choices=[('VENDOR', 'Vendor'), ('STAFF', 'Staff'), ('USER', 'User')], default='USER',
                                  max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles',
                                              to='accounts.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
