import os
import pytz
from garage_core.settings import  TIME_ZONE

# SECURITY WARNING: keep the secret key used in production secret!

TZ = pytz.timezone(TIME_ZONE)
COOKIES_EXPIRY_SECONDS = 300
COOKIES_SECURE = False
DOMAIN = os.environ.get('DOMAIN', 'localhost')
ROLE_VENDOR = 'VENDOR'

ROLE_STAFF = 'STAFF'

ROLE_USER = 'USER'
EMAIL_VERIFICATION_CODE_EXPIRY = 300
EMAIL_VERIFICATION_CODE_LENGTH = 6
EMAIL_VERIFICATION_CODE_ATTEMPTS = 3
EMAIL_VERIFICATION_CODE_ATTEMPTS_LOCK = 3
CAN_RESEND_EMAIL_TIMEOUT = 300
EMAIL_VERIFICATION_CODE_EXPIRY = 300

USER_ROLE_CHOICES = (
    (ROLE_VENDOR, ROLE_VENDOR.title()),
    (ROLE_STAFF, ROLE_STAFF.title()),
    (ROLE_USER, ROLE_USER.title()),
)

PROVINCE_CENTRAL = 'CENTRAL'

PROVINCE_COPPERBELT = 'COPPERBELT'

PROVINCE_EASTERN = 'EASTERN'

PROVINCE_LUAPULA = 'LUAPULA'

PROVINCE_LUSAKA = 'LUSAKA'

PROVINCE_MUCHINGA = 'MUCHINGA'

PROVINCE_NORTH_WESTERN = 'NORTH-WESTERN'

PROVINCE_NORTH = 'NORTH'

PROVINCE_SOUTHERN = 'SOUTHERN'

PROVINCE_WESTERN = 'WESTERN'

PROVINCE_CHOICES = (
    (PROVINCE_CENTRAL, PROVINCE_CENTRAL.title()),
    (PROVINCE_COPPERBELT, PROVINCE_COPPERBELT.title()),
    (PROVINCE_EASTERN, PROVINCE_EASTERN.title()),
    (PROVINCE_LUAPULA, PROVINCE_LUAPULA.title()),
    (PROVINCE_LUSAKA, PROVINCE_LUSAKA.title()),
    (PROVINCE_MUCHINGA, PROVINCE_MUCHINGA.title()),
    (PROVINCE_NORTH_WESTERN, PROVINCE_NORTH_WESTERN.title()),
    (PROVINCE_NORTH, PROVINCE_NORTH.title()),
    (PROVINCE_SOUTHERN, PROVINCE_SOUTHERN.title()),
    (PROVINCE_WESTERN, PROVINCE_WESTERN.title()),
)
