import os
import pytz
from garage_core.settings import  TIME_ZONE

# SECURITY WARNING: keep the secret key used in production secret!

TZ = pytz.timezone(TIME_ZONE)
COOKIES_EXPIRY_SECONDS = 300
COOKIES_SECURE = False
DOMAIN = os.environ.get('DOMAIN', 'localhost')
ROLE_VENDOR = 'VENDOR'

ROLE_STAFF = 'STAFF'

ROLE_USER = 'USER'
EMAIL_VERIFICATION_CODE_EXPIRY = 300
EMAIL_VERIFICATION_CODE_LENGTH = 6
EMAIL_VERIFICATION_CODE_ATTEMPTS = 3
EMAIL_VERIFICATION_CODE_ATTEMPTS_LOCK = 3
CAN_RESEND_EMAIL_TIMEOUT = 300
EMAIL_VERIFICATION_CODE_EXPIRY = 300

USER_ROLE_CHOICES = (
    (ROLE_VENDOR, ROLE_VENDOR.title()),
    (ROLE_STAFF, ROLE_STAFF.title()),
    (ROLE_USER, ROLE_USER.title()),
)

PROVINCE_CENTRAL = 'CENTRAL'

PROVINCE_COPPERBELT = 'COPPERBELT'

PROVINCE_EASTERN = 'EASTERN'

PROVINCE_LUAPULA = 'LUAPULA'

PROVINCE_LUSAKA = 'LUSAKA'

PROVINCE_MUCHINGA = 'MUCHINGA'

PROVINCE_NORTH_WESTERN = 'NORTH-WESTERN'

PROVINCE_NORTH = 'NORTH'

PROVINCE_SOUTHERN = 'SOUTHERN'

PROVINCE_WESTERN = 'WESTERN'

PROVINCE_CHOICES = (
    (PROVINCE_CENTRAL, PROVINCE_CENTRAL.title()),
    (PROVINCE_COPPERBELT, PROVINCE_COPPERBELT.title()),
    (PROVINCE_EASTERN, PROVINCE_EASTERN.title()),
    (PROVINCE_LUAPULA, PROVINCE_LUAPULA.title()),
    (PROVINCE_LUSAKA, PROVINCE_LUSAKA.title()),
    (PROVINCE_MUCHINGA, PROVINCE_MUCHINGA.title()),
    (PROVINCE_NORTH_WESTERN, PROVINCE_NORTH_WESTERN.title()),
    (PROVINCE_NORTH, PROVINCE_NORTH.title()),
    (PROVINCE_SOUTHERN, PROVINCE_SOUTHERN.title()),
    (PROVINCE_WESTERN, PROVINCE_WESTERN.title()),
)
SEND_BLUE_API_KEY = os.getenv('SEND_BLUE_API_KEY')
TYPE_SMS = 'SMS'

TYPE_EMAIL = 'EMAIL'

COMMUNICATION_TYPE = (
    (TYPE_SMS, TYPE_SMS),
    (TYPE_EMAIL, TYPE_EMAIL),
)

STATUS_PENDING = 'PENDING'

STATUS_SENT = 'SENT'

STATUS_DENIED = 'DENIED'

STATUS_FAILED = 'FAILED'

COMMUNICATION_STATUS_CHOICES = (
    (STATUS_PENDING, STATUS_PENDING),
    (STATUS_SENT, STATUS_SENT),
    (STATUS_FAILED, STATUS_FAILED),
    (STATUS_DENIED, STATUS_DENIED),
)
WEBSITE_NAME = 'Garage.com'
SEND_BLUE_SENDER_EMAIL = 'no_reply@garagelimited.info'
MAIL_SUBJECT = 'Garage.com'
TEXT_CONTENT = ''
NOREPLY_MAIL=''
TYPE_EMAIL = ''
COD = 'COD'
CURRENCY_SYMBOL= 'Kshs'
ORDER_CONFIRMATION_SUBJECT = "THANK YOU FOR YOUR ORDER"

ORDER_SELLER_SUBJECT = "YOU RECEIVED AN ORDER"

SHIPMENT_TRACKING_LINK = 'to be updated'

ORDER_IN_PROGRESS_SUBJECT = "YOUR ORDER IS IN PROGRESS"

ORDER_FAILURE_SUBJECT = "YOUR ORDER HAS FAILED"

RESET_PASSWORD_SUBJECT = 'RESET PASSWORD'

if os.environ.get('mode') == 'production':
    COOKIES_SECURE = True
else:
    COOKIES_SECURE = False